- name: Persist a workflow and related objects from an Ansible Tower
  hosts: all
  gather_facts: false
  vars:
    tower_host: ""
    tower_port: 443
    src_workflow_id: 0
    git_repo_uri: ""
    git_branch: "master"
    git_user_name: ""
    git_user_email: ""
    git_binary_path: "/usr/bin/git"
    private_key_path: ""
    commit_msg: "Updated via Ansible"
  tasks:

    - name: Check variables
      assert:
        that:
          - tower_host != ""
          - git_repo_uri != ""
          - src_workflow_id != 0
          - private_key_path != ""
          - git_user_name != ""
          - git_user_email != ""
          - commit_msg != ""
        fail_msg: "The required variables are not correctly set."
    
    - name: Get the source workflow representation
      uri:
        url: "https://{{ tower_host }}:{{ tower_port }}/api/v2/workflow_job_templates/{{ src_workflow_id }}/"
        force_basic_auth: yes
        method: GET
        validate_certs: no
        user: "{{ tower_user }}"
        password: "{{ tower_password }}"
      register: response

    - name: Infer the workflow name and define it as a variable
      set_fact:
        workflow_name: "{{ response.json.name }}"

    - name: Set the path for the checkout folder
      set_fact:
        git_checkout_folder_path: "/tmp/git-{{ workflow_name }}-{{ src_workflow_id }}"

    - name:
      git:
        repo: "{{ git_repo_uri }}"
        # Replace with tmp cleanable directory
        dest: "{{ git_checkout_folder_path }}"
        depth: 1
        force: yes
        accept_hostkey: yes
        key_file: "{{ private_key_path }}"
        executable: "{{ git_binary_path }}"

    - name: Persist workflow file
      copy:
        dest: "{{ git_checkout_folder_path }}/workflow.json"
        content: "{{ response.json|to_nice_json }}"

    - name: Get Git version
      command: "{{ git_binary_path }} --version"
      register: git_version

    - debug:
        msg: "Using Git version: {{ git_version.stdout }}"

    - name: Git add files
      command:
        chdir: "{{ git_checkout_folder_path }}"
        cmd: "{{ git_binary_path }} add ."

    - name: Commit
      command:
        chdir: "{{ git_checkout_folder_path }}"
        cmd: "{{ git_binary_path }} -c user.name='{{ git_user_name }}' -c user.email='<{{ git_user_email }}>' commit -m '{{ commit_msg }}' "

    - name: Push
      command:
        chdir: "{{ git_checkout_folder_path }}"
        cmd: "{{ git_binary_path }} push origin master"
      environment:
        GIT_SSH_COMMAND: ssh -i "{{ private_key_path }}"

