- name: Persist a workflow and related objects from an Ansible Tower
  hosts: all
  gather_facts: false
  force_handlers: true
  vars:
    tower_host: ""
    tower_port: 443
    src_workflow_id: 0
    tower_object_type: "workflow_job_template"
    git_repo_uri: ""
    git_branch: "master"
    git_user_name: ""
    git_user_email: ""
    git_binary_path: "/usr/bin/git"
    private_key_path: ""
    commit_msg: "Updated via Ansible"
  tasks:

    # --- Checks

    - name: Check variables
      assert:
        that:
          - tower_host != ""
          - git_repo_uri != ""
          - src_workflow_id != 0
          - private_key_path != ""
          - git_user_name != ""
          - git_user_email != ""
          - commit_msg != ""
        fail_msg: "The required variables are not correctly set."

    # --- Preparation
    
    - name: Generate random directory for checkout
      set_fact:
        git_checkout_path: "/tmp/persist-workflow-{{ lookup('password', '/dev/null chars=hexdigits length=16') }}"

    - debug:
        msg: "Creating {{ git_checkout_path }}"

    - name:
      git:
        repo: "{{ git_repo_uri }}"
        # Replace with tmp cleanable directory
        dest: "{{ git_checkout_path }}"
        depth: 1
        force: yes
        accept_hostkey: yes
        key_file: "{{ private_key_path }}"
        executable: "{{ git_binary_path }}"
      notify:
        - test
        - delete git checkout folder

    - assert:
        that: 1 == 0

    # --- Fetch objects
    
    - name: Get the source workflow representation
      uri:
        url: "https://{{ tower_host }}:{{ tower_port }}/api/v2/{{ tower_object_type }}s/{{ src_workflow_id }}/"
        force_basic_auth: yes
        method: GET
        validate_certs: no
        user: "{{ tower_user }}"
        password: "{{ tower_password }}"
      register: response

    - name: Infer the workflow name and define it as a variable
      set_fact:
        src_workflow_name: "{{ response.json.name }}"
      when: tower_object_type == "workflow_job_template"

    - name: Define the path of the namespaced directory that will contain the file
      set_fact:
        namespace_path: "{{ git_checkout_path }}/{{ tower_object_type }}s"

    - name: create directory if they don't exist
      file:
        path: "{{ namespace_path }}"
        state: directory

    - name: Persist workflow file
      copy:
        dest: "{{ namespace_path }}/{{ src_workflow_name }}.json"
        content: "{{ response.json|to_nice_json }}"

    - name: Get Git version
      command: "{{ git_binary_path }} --version"
      register: git_version

    - debug:
        msg: "Using Git version: {{ git_version.stdout }}"

    - name: Git add files
      command:
        chdir: "{{ git_checkout_path }}"
        cmd: "{{ git_binary_path }} add ."

    - name: Commit
      command:
        chdir: "{{ git_checkout_path }}"
        cmd: "{{ git_binary_path }} -c user.name='{{ git_user_name }}' -c user.email='<{{ git_user_email }}>' commit -m '{{ commit_msg }}' "

    - name: Push
      command:
        chdir: "{{ git_checkout_path }}"
        cmd: "{{ git_binary_path }} push origin master"
      environment:
        GIT_SSH_COMMAND: ssh -i "{{ private_key_path }}"

  handlers:

    - name: test
      debug:
        msg: "Triggered!"

    - name: delete git checkout folder
      file:
        path: "{{ git_checkout_path }}"
        state: absent

