- name: Update a workflow from Git
  hosts: all
  gather_facts: false
  vars:
    tower_host: ""
    tower_port: 443
    tgt_workflow_id: 0
    git_repo_uri: ""
    git_branch: "master"
    git_binary_path: "/usr/bin/git"
    private_key_path: ""
  tasks:

    - name: Check variables
      assert:
        that:
          - tower_host != ""
          - git_repo_uri != ""
          - tgt_workflow_id != 0
        fail_msg: "Variables not correctly set."
    
    - name: Get the target workflow representation
      uri:
        url: "https://{{ tower_host }}:{{ tower_port }}/api/v2/workflow_job_templates/{{ tgt_workflow_id }}/"
        force_basic_auth: yes
        method: GET
        validate_certs: no
        user: "{{ tower_user }}"
        password: "{{ tower_password }}"
      register: response

    - name: Infer the org and workflow names and define them as variables
      set_fact:
        tgt_workflow_name: "{{ response.json.name }}"
        org_id: "{{ response.json.organization }}"

    - assert:
        that:
          - org_id != ""
        fail_msg: "The target workflow must be associated with an organization."

    - name: Set the path for the checkout folder
      set_fact:
        git_checkout_folder_path: "/tmp/git-work-{{ tgt_workflow_id }}"

    - name:
      git:
        repo: "{{ git_repo_uri }}"
        # Replace with tmp cleanable directory
        dest: "{{ git_checkout_folder_path }}"
        depth: 1
        force: yes
        accept_hostkey: yes
        key_file: "{{ private_key_path }}"
        executable: "{{ git_binary_path }}"

    - name: Get the source workflow data
      slurp:
        src: "{{ git_checkout_folder_path}}/workflow_job_templates/{{ tgt_workflow_name }}.json"
      register: src_workflow_json

    - name: Infer some metadata from the data
      set_fact:
        src_workflow_data: "{{ src_workflow_json['content'] | b64decode | from_json }}"

    - assert:
        that:
          - src_workflow_data['name'] == tgt_workflow_name
        fail_msg: "The source and target workflows must have the same name."

    - name: Alter the JSON to change the organization
      set_fact:
        tgt_workflow_new_data: "{{ src_workflow_data | combine({'organization': org_id}) }}"

    - name: Put the new target workflow representation
      uri:
        url: "https://{{ tower_host }}:{{ tower_port }}/api/v2/workflow_job_templates/{{ tgt_workflow_id }}/"
        force_basic_auth: yes
        method: PUT
        body_format: json
        body: "{{ tgt_workflow_new_data }}"
        validate_certs: no
        user: "{{ tower_user }}"
        password: "{{ tower_password }}"
