- name: Update a workflow from Git
  hosts: all
  gather_facts: false
  vars:
    tower_host: ""
    tower_port: 443
    workflow_id: 0
    git_repo_uri: ""
    git_branch: "master"
  tasks:

    - name: Check variables
      assert:
        that:
          - tower_host != ""
          - git_repo_uri != ""
          - workflow_id != 0
        fail_msg: "Variables not correctly set."
    
    - name: Get the target workflow representation
      uri:
        url: "https://{{ tower_host }}:{{ tower_port }}/api/v2/workflow_job_templates/{{ workflow_id }}/"
        force_basic_auth: yes
        method: GET
        validate_certs: no
        user: "{{ tower_user }}"
        password: "{{ tower_password }}"
      register: response

    - name: Print the result
      debug:
        msg: "{{ response.json }}"

    - name: Set the workflow name
      set_fact:
        workflow_name: "{{ response.json.name }}"
        org_id: "{{ response.json.organization }}"

    - assert:
        that:
          - org_id != ""

    - name: Set the path for the checkout folder
      set_fact:
        git_checkout_folder_path: "/tmp/git-work-{{ workflow_id }}"

    - name:
      git:
        repo: "{{ git_repo_uri }}"
        # Replace with tmp cleanable directory
        dest: "{{ git_checkout_folder_path }}"
        depth: 1
        force: yes
        accept_hostkey: yes

    - name: Get the contents of the workflow
      slurp:
        src: "{{ git_checkout_folder_path}}/workflow.json"
      register: workflow_json

    - name: Alter the JSON to change the organization
      set_fact:
        workflow_final: "{{ workflow_json['content'] | b64decode | from_json | combine({'organization': org_id}) }}"

    - debug:
        msg: "FLOW: {{ workflow_final }}"

    - name: Put the new target workflow representation
      uri:
        url: "https://{{ tower_host }}:{{ tower_port }}/api/v2/workflow_job_templates/{{ workflow_id }}/"
        force_basic_auth: yes
        method: PUT
        body_format: json
        body: "{{ workflow_final }}"
        validate_certs: no
        user: "{{ tower_user }}"
        password: "{{ tower_password }}"
      register: response2

    - debug:
        msg: "{{ response2 }}"
